using UtilityHub360.DTOs;
using UtilityHub360.Models;

namespace UtilityHub360.Services
{
    /// <summary>
    /// Interface for bill analytics and forecasting services
    /// </summary>
    public interface IBillAnalyticsService
    {
        // Analytics Calculations
        Task<ApiResponse<BillHistoryWithAnalyticsDto>> GetBillHistoryWithAnalyticsAsync(
            string userId, 
            string? provider = null, 
            string? billType = null, 
            int months = 6);

        Task<ApiResponse<BillAnalyticsCalculationsDto>> CalculateAnalyticsAsync(
            string userId, 
            string? provider = null, 
            string? billType = null, 
            int months = 6);

        Task<ApiResponse<decimal>> CalculateSimpleAverageAsync(
            string userId, 
            string provider, 
            string billType, 
            int months = 3);

        Task<ApiResponse<decimal>> CalculateWeightedAverageAsync(
            string userId, 
            string provider, 
            string billType, 
            int months = 3);

        Task<ApiResponse<decimal>> CalculateSeasonalAverageAsync(
            string userId, 
            string provider, 
            string billType);

        // Forecasting
        Task<ApiResponse<BillForecastDto>> GetForecastAsync(
            string userId, 
            string provider, 
            string billType, 
            string method = "weighted");

        // Variance Analysis
        Task<ApiResponse<BillVarianceDto>> CalculateVarianceAsync(
            string billId, 
            string userId);

        // Budget Management
        Task<ApiResponse<BudgetSettingDto>> CreateBudgetAsync(
            CreateBudgetSettingDto budgetDto, 
            string userId);

        Task<ApiResponse<BudgetSettingDto>> UpdateBudgetAsync(
            string budgetId, 
            CreateBudgetSettingDto budgetDto, 
            string userId);

        Task<ApiResponse<bool>> DeleteBudgetAsync(
            string budgetId, 
            string userId);

        Task<ApiResponse<BudgetSettingDto>> GetBudgetAsync(
            string budgetId, 
            string userId);

        Task<ApiResponse<List<BudgetSettingDto>>> GetUserBudgetsAsync(
            string userId);

        Task<ApiResponse<BudgetStatusDto>> GetBudgetStatusAsync(
            string userId, 
            string provider, 
            string billType);

        // Alerts
        Task<ApiResponse<List<BillAlertDto>>> GetUserAlertsAsync(
            string userId, 
            bool? isRead = null, 
            int limit = 50);

        Task<ApiResponse<bool>> MarkAlertAsReadAsync(
            string alertId, 
            string userId);

        Task<ApiResponse<List<BillAlertDto>>> GenerateAlertsAsync(
            string userId);

        // Provider Analytics
        Task<ApiResponse<List<ProviderAnalyticsDto>>> GetProviderAnalyticsAsync(
            string userId, 
            int months = 6);

        Task<ApiResponse<ProviderAnalyticsDto>> GetProviderAnalyticsByProviderAsync(
            string userId, 
            string provider, 
            string billType, 
            int months = 6);

        // Dashboard
        Task<ApiResponse<BillDashboardDto>> GetDashboardDataAsync(
            string userId);

        // Monthly Summaries
        Task<ApiResponse<List<MonthlyBillSummaryDto>>> GetMonthlyTrendAsync(
            string userId, 
            string? provider = null, 
            string? billType = null, 
            int months = 12);

        // Auto-Recurring Bill Generation
        Task<ApiResponse<BillDto>> AutoGenerateNextMonthBillAsync(
            string userId, 
            string provider, 
            string billType);

        Task<ApiResponse<List<BillDto>>> AutoGenerateAllRecurringBillsAsync(
            string userId);

        Task<ApiResponse<BillDto>> ConfirmAutoGeneratedBillAsync(
            string billId, 
            ConfirmBillAmountDto confirmDto, 
            string userId);

        Task<ApiResponse<List<BillDto>>> GetAutoGeneratedBillsAsync(
            string userId, 
            bool? confirmed = null);
    }
}

