using UtilityHub360.DTOs;
using UtilityHub360.Entities;
using UtilityHub360.Models;

namespace UtilityHub360.Services
{
    public interface IBillService
    {
        // CRUD Operations
        Task<ApiResponse<BillDto>> CreateBillAsync(CreateBillDto createBillDto, string userId);
        Task<ApiResponse<BillDto>> GetBillAsync(string billId, string userId);
        Task<ApiResponse<BillDto>> UpdateBillAsync(string billId, UpdateBillDto updateBillDto, string userId);
        Task<ApiResponse<bool>> DeleteBillAsync(string billId, string userId);
        Task<ApiResponse<PaginatedResponse<BillDto>>> GetUserBillsAsync(string userId, string? status, string? billType, int page, int limit);

        // Analytics and Reporting
        Task<ApiResponse<decimal>> GetTotalPendingAmountAsync(string userId);
        Task<ApiResponse<BillSummaryDto>> GetTotalPaidAmountAsync(string userId, string period); // week, month, quarter, year
        Task<ApiResponse<decimal>> GetTotalOverdueAmountAsync(string userId);
        Task<ApiResponse<BillAnalyticsDto>> GetBillAnalyticsAsync(string userId);

        // Bill Management
        Task<ApiResponse<BillDto>> MarkBillAsPaidAsync(string billId, string userId, string? notes, string? bankAccountId = null);
        Task<ApiResponse<bool>> UpdateBillStatusAsync(string billId, string status, string userId);
        Task<ApiResponse<List<BillDto>>> GetOverdueBillsAsync(string userId);
        Task<ApiResponse<List<BillDto>>> GetUpcomingBillsAsync(string userId, int days = 7);

        // Admin Operations
        Task<ApiResponse<PaginatedResponse<BillDto>>> GetAllBillsAsync(string? status, string? billType, int page, int limit);

        // Bill Payment Operations
        Task<ApiResponse<BillPaymentDto>> MakeBillPaymentAsync(CreateBillPaymentDto payment, string userId);
        Task<ApiResponse<List<BillPaymentDto>>> GetBillPaymentHistoryAsync(string billId, string userId, int page = 1, int limit = 50);
        Task<ApiResponse<BillPaymentDto>> GetBillPaymentAsync(string paymentId, string userId);
        Task<ApiResponse<bool>> DeleteBillPaymentAsync(string paymentId, string userId);

        // Monthly Bill Management
        Task<ApiResponse<List<BillDto>>> GetBillsByMonthAsync(string userId, int year, int month, string? provider = null, string? billType = null);
        Task<ApiResponse<BillDto>> UpdateMonthlyBillAsync(string billId, UpdateMonthlyBillDto updateDto, string userId);

        // Auto-Generated Bills Cleanup Operations
        Task<ApiResponse<CleanupResultDto>> CleanupOutOfYearAutoGeneratedBillsAsync(string userId);
        Task<ApiResponse<OutOfYearBillsCountDto>> GetOutOfYearAutoGeneratedBillsCountAsync(string userId);
        Task<ApiResponse<CleanupResultDto>> DeleteAutoGeneratedBillsByDateRangeAsync(string userId, DateTime startDate, DateTime endDate);
        Task<ApiResponse<DateRangeBillsCountDto>> GetAutoGeneratedBillsCountByDateRangeAsync(string userId, DateTime startDate, DateTime endDate);
    }
}
