using Microsoft.EntityFrameworkCore;
using UtilityHub360.Data;
using UtilityHub360.DTOs;
using UtilityHub360.Entities;
using UtilityHub360.Models;

namespace UtilityHub360.Services
{
    public class UtilityService : IUtilityService
    {
        private readonly ApplicationDbContext _context;
        private readonly AccountingService _accountingService;

        public UtilityService(ApplicationDbContext context, AccountingService accountingService)
        {
            _context = context;
            _accountingService = accountingService;
        }

        public async Task<ApiResponse<UtilityDto>> CreateUtilityAsync(CreateUtilityDto createUtilityDto, string userId)
        {
            try
            {
                // Calculate consumption if readings are provided
                decimal? consumption = null;
                if (createUtilityDto.CurrentReading.HasValue && createUtilityDto.PreviousReading.HasValue)
                {
                    consumption = createUtilityDto.CurrentReading.Value - createUtilityDto.PreviousReading.Value;
                }

                // Calculate cost per unit if consumption and amount are provided
                decimal? costPerUnit = null;
                if (consumption.HasValue && consumption.Value > 0 && createUtilityDto.Amount > 0)
                {
                    costPerUnit = createUtilityDto.Amount / consumption.Value;
                }
                else if (createUtilityDto.CostPerUnit.HasValue)
                {
                    costPerUnit = createUtilityDto.CostPerUnit.Value;
                }

                var utility = new Utility
                {
                    Id = Guid.NewGuid().ToString(),
                    UserId = userId,
                    UtilityName = createUtilityDto.UtilityName,
                    UtilityType = createUtilityDto.UtilityType.ToUpper(),
                    Provider = createUtilityDto.Provider,
                    AccountNumber = createUtilityDto.AccountNumber,
                    Unit = createUtilityDto.Unit,
                    Consumption = consumption ?? createUtilityDto.Consumption,
                    CostPerUnit = costPerUnit,
                    Amount = createUtilityDto.Amount,
                    BillingDate = createUtilityDto.BillingDate,
                    DueDate = createUtilityDto.DueDate,
                    Status = "PENDING",
                    Notes = createUtilityDto.Notes,
                    ReferenceNumber = createUtilityDto.ReferenceNumber,
                    PreviousReading = createUtilityDto.PreviousReading,
                    CurrentReading = createUtilityDto.CurrentReading,
                    ReadingDate = createUtilityDto.ReadingDate,
                    PropertyAddress = createUtilityDto.PropertyAddress,
                    MeterNumber = createUtilityDto.MeterNumber,
                    AutoGenerateNext = createUtilityDto.AutoGenerateNext,
                    IsAutoGenerated = false,
                    CreatedAt = DateTime.UtcNow,
                    UpdatedAt = DateTime.UtcNow
                };

                _context.Utilities.Add(utility);
                await _context.SaveChangesAsync();

                // Create accrual accounting entry
                await _accountingService.CreateBillAccrualEntryAsync(
                    utility.Id,
                    userId,
                    createUtilityDto.Amount,
                    createUtilityDto.UtilityName,
                    "UTILITY",
                    createUtilityDto.ReferenceNumber,
                    $"Utility bill received: {createUtilityDto.UtilityName}",
                    DateTime.UtcNow
                );

                var utilityDto = MapToDto(utility);
                return ApiResponse<UtilityDto>.SuccessResult(utilityDto, "Utility created successfully");
            }
            catch (Exception ex)
            {
                return ApiResponse<UtilityDto>.ErrorResult($"Failed to create utility: {ex.Message}");
            }
        }

        public async Task<ApiResponse<UtilityDto>> GetUtilityAsync(string utilityId, string userId)
        {
            try
            {
                var utility = await _context.Utilities
                    .FirstOrDefaultAsync(u => u.Id == utilityId && u.UserId == userId && !u.IsDeleted);

                if (utility == null)
                {
                    return ApiResponse<UtilityDto>.ErrorResult("Utility not found");
                }

                var utilityDto = MapToDto(utility);
                return ApiResponse<UtilityDto>.SuccessResult(utilityDto);
            }
            catch (Exception ex)
            {
                return ApiResponse<UtilityDto>.ErrorResult($"Failed to get utility: {ex.Message}");
            }
        }

        public async Task<ApiResponse<UtilityDto>> UpdateUtilityAsync(string utilityId, UpdateUtilityDto updateUtilityDto, string userId)
        {
            try
            {
                var utility = await _context.Utilities
                    .FirstOrDefaultAsync(u => u.Id == utilityId && u.UserId == userId && !u.IsDeleted);

                if (utility == null)
                {
                    return ApiResponse<UtilityDto>.ErrorResult("Utility not found");
                }

                // Update fields
                if (!string.IsNullOrEmpty(updateUtilityDto.UtilityName))
                    utility.UtilityName = updateUtilityDto.UtilityName;

                if (!string.IsNullOrEmpty(updateUtilityDto.UtilityType))
                    utility.UtilityType = updateUtilityDto.UtilityType.ToUpper();

                if (!string.IsNullOrEmpty(updateUtilityDto.Provider))
                    utility.Provider = updateUtilityDto.Provider;

                if (updateUtilityDto.AccountNumber != null)
                    utility.AccountNumber = updateUtilityDto.AccountNumber;

                if (updateUtilityDto.Unit != null)
                    utility.Unit = updateUtilityDto.Unit;

                if (updateUtilityDto.Amount.HasValue)
                    utility.Amount = updateUtilityDto.Amount.Value;

                if (updateUtilityDto.BillingDate.HasValue)
                    utility.BillingDate = updateUtilityDto.BillingDate.Value;

                if (updateUtilityDto.DueDate.HasValue)
                    utility.DueDate = updateUtilityDto.DueDate.Value;

                if (updateUtilityDto.Notes != null)
                    utility.Notes = updateUtilityDto.Notes;

                if (updateUtilityDto.ReferenceNumber != null)
                    utility.ReferenceNumber = updateUtilityDto.ReferenceNumber;

                if (updateUtilityDto.PreviousReading.HasValue)
                    utility.PreviousReading = updateUtilityDto.PreviousReading;

                if (updateUtilityDto.CurrentReading.HasValue)
                    utility.CurrentReading = updateUtilityDto.CurrentReading;

                if (updateUtilityDto.ReadingDate.HasValue)
                    utility.ReadingDate = updateUtilityDto.ReadingDate;

                if (updateUtilityDto.PropertyAddress != null)
                    utility.PropertyAddress = updateUtilityDto.PropertyAddress;

                if (updateUtilityDto.MeterNumber != null)
                    utility.MeterNumber = updateUtilityDto.MeterNumber;

                if (updateUtilityDto.AutoGenerateNext.HasValue)
                    utility.AutoGenerateNext = updateUtilityDto.AutoGenerateNext.Value;

                // Recalculate consumption if readings changed
                if (updateUtilityDto.CurrentReading.HasValue || updateUtilityDto.PreviousReading.HasValue)
                {
                    var currentReading = updateUtilityDto.CurrentReading ?? utility.CurrentReading;
                    var previousReading = updateUtilityDto.PreviousReading ?? utility.PreviousReading;

                    if (currentReading.HasValue && previousReading.HasValue)
                    {
                        utility.Consumption = currentReading.Value - previousReading.Value;
                    }
                }

                // Recalculate cost per unit
                if (utility.Consumption.HasValue && utility.Consumption.Value > 0 && utility.Amount > 0)
                {
                    utility.CostPerUnit = utility.Amount / utility.Consumption.Value;
                }
                else if (updateUtilityDto.CostPerUnit.HasValue)
                {
                    utility.CostPerUnit = updateUtilityDto.CostPerUnit.Value;
                }

                utility.UpdatedAt = DateTime.UtcNow;
                await _context.SaveChangesAsync();

                var utilityDto = MapToDto(utility);
                return ApiResponse<UtilityDto>.SuccessResult(utilityDto, "Utility updated successfully");
            }
            catch (Exception ex)
            {
                return ApiResponse<UtilityDto>.ErrorResult($"Failed to update utility: {ex.Message}");
            }
        }

        public async Task<ApiResponse<bool>> DeleteUtilityAsync(string utilityId, string userId)
        {
            try
            {
                var utility = await _context.Utilities
                    .FirstOrDefaultAsync(u => u.Id == utilityId && u.UserId == userId && !u.IsDeleted);

                if (utility == null)
                {
                    return ApiResponse<bool>.ErrorResult("Utility not found");
                }

                // Soft delete
                utility.IsDeleted = true;
                utility.DeletedAt = DateTime.UtcNow;
                utility.DeletedBy = userId;
                utility.UpdatedAt = DateTime.UtcNow;

                await _context.SaveChangesAsync();
                return ApiResponse<bool>.SuccessResult(true, "Utility deleted successfully");
            }
            catch (Exception ex)
            {
                return ApiResponse<bool>.ErrorResult($"Failed to delete utility: {ex.Message}");
            }
        }

        public async Task<ApiResponse<PaginatedResponse<UtilityDto>>> GetUserUtilitiesAsync(string userId, string? status, string? utilityType, int page, int limit)
        {
            try
            {
                var query = _context.Utilities
                    .Where(u => u.UserId == userId && !u.IsDeleted)
                    .AsQueryable();

                if (!string.IsNullOrEmpty(status))
                {
                    query = query.Where(u => u.Status.ToUpper() == status.ToUpper());
                }

                if (!string.IsNullOrEmpty(utilityType))
                {
                    query = query.Where(u => u.UtilityType.ToUpper() == utilityType.ToUpper());
                }

                var totalCount = await query.CountAsync();
                var utilities = await query
                    .OrderByDescending(u => u.BillingDate)
                    .Skip((page - 1) * limit)
                    .Take(limit)
                    .ToListAsync();

                var utilityDtos = utilities.Select(MapToDto).ToList();

                var paginatedResponse = new PaginatedResponse<UtilityDto>
                {
                    Data = utilityDtos,
                    Page = page,
                    Limit = limit,
                    TotalCount = totalCount
                };

                return ApiResponse<PaginatedResponse<UtilityDto>>.SuccessResult(paginatedResponse);
            }
            catch (Exception ex)
            {
                return ApiResponse<PaginatedResponse<UtilityDto>>.ErrorResult($"Failed to get utilities: {ex.Message}");
            }
        }

        public async Task<ApiResponse<decimal>> GetTotalPendingAmountAsync(string userId)
        {
            try
            {
                var total = await _context.Utilities
                    .Where(u => u.UserId == userId && u.Status == "PENDING" && !u.IsDeleted)
                    .SumAsync(u => u.Amount);

                return ApiResponse<decimal>.SuccessResult(total);
            }
            catch (Exception ex)
            {
                return ApiResponse<decimal>.ErrorResult($"Failed to get total pending amount: {ex.Message}");
            }
        }

        public async Task<ApiResponse<decimal>> GetTotalPaidAmountAsync(string userId, string period)
        {
            try
            {
                var query = _context.Utilities
                    .Where(u => u.UserId == userId && u.Status == "PAID" && !u.IsDeleted);

                var now = DateTime.UtcNow;
                switch (period.ToLower())
                {
                    case "week":
                        query = query.Where(u => u.PaidAt >= now.AddDays(-7));
                        break;
                    case "month":
                        query = query.Where(u => u.PaidAt >= now.AddMonths(-1));
                        break;
                    case "quarter":
                        query = query.Where(u => u.PaidAt >= now.AddMonths(-3));
                        break;
                    case "year":
                        query = query.Where(u => u.PaidAt >= now.AddYears(-1));
                        break;
                }

                var total = await query.SumAsync(u => u.Amount);
                return ApiResponse<decimal>.SuccessResult(total);
            }
            catch (Exception ex)
            {
                return ApiResponse<decimal>.ErrorResult($"Failed to get total paid amount: {ex.Message}");
            }
        }

        public async Task<ApiResponse<decimal>> GetTotalOverdueAmountAsync(string userId)
        {
            try
            {
                var now = DateTime.UtcNow;
                var total = await _context.Utilities
                    .Where(u => u.UserId == userId && 
                               u.Status == "PENDING" && 
                               u.DueDate < now && 
                               !u.IsDeleted)
                    .SumAsync(u => u.Amount);

                return ApiResponse<decimal>.SuccessResult(total);
            }
            catch (Exception ex)
            {
                return ApiResponse<decimal>.ErrorResult($"Failed to get total overdue amount: {ex.Message}");
            }
        }

        public async Task<ApiResponse<UtilityAnalyticsDto>> GetUtilityAnalyticsAsync(string userId)
        {
            try
            {
                var utilities = await _context.Utilities
                    .Where(u => u.UserId == userId && !u.IsDeleted)
                    .ToListAsync();

                var now = DateTime.UtcNow;
                var pendingAmount = utilities.Where(u => u.Status == "PENDING").Sum(u => u.Amount);
                var paidAmount = utilities.Where(u => u.Status == "PAID").Sum(u => u.Amount);
                var overdueAmount = utilities.Where(u => u.Status == "PENDING" && u.DueDate < now).Sum(u => u.Amount);

                var byType = utilities
                    .GroupBy(u => u.UtilityType)
                    .Select(g => new UtilityTypeSummaryDto
                    {
                        UtilityType = g.Key,
                        TotalAmount = g.Sum(u => u.Amount),
                        TotalConsumption = g.Sum(u => u.Consumption),
                        AverageCostPerUnit = g.Where(u => u.Consumption.HasValue && u.Consumption.Value > 0)
                            .Average(u => u.Amount / u.Consumption.Value),
                        Count = g.Count()
                    })
                    .ToList();

                var byProvider = utilities
                    .GroupBy(u => new { u.Provider, u.UtilityType })
                    .Select(g => new ProviderSummaryDto
                    {
                        Provider = g.Key.Provider,
                        UtilityType = g.Key.UtilityType,
                        TotalAmount = g.Sum(u => u.Amount),
                        TotalConsumption = g.Sum(u => u.Consumption),
                        AverageCostPerUnit = g.Where(u => u.Consumption.HasValue && u.Consumption.Value > 0)
                            .Average(u => u.Amount / u.Consumption.Value),
                        Count = g.Count()
                    })
                    .ToList();

                var analytics = new UtilityAnalyticsDto
                {
                    TotalPendingAmount = pendingAmount,
                    TotalPaidAmount = paidAmount,
                    TotalOverdueAmount = overdueAmount,
                    TotalUtilities = utilities.Count,
                    PendingCount = utilities.Count(u => u.Status == "PENDING"),
                    PaidCount = utilities.Count(u => u.Status == "PAID"),
                    OverdueCount = utilities.Count(u => u.Status == "PENDING" && u.DueDate < now),
                    ByType = byType,
                    ByProvider = byProvider
                };

                return ApiResponse<UtilityAnalyticsDto>.SuccessResult(analytics);
            }
            catch (Exception ex)
            {
                return ApiResponse<UtilityAnalyticsDto>.ErrorResult($"Failed to get utility analytics: {ex.Message}");
            }
        }

        public async Task<ApiResponse<UtilityDto>> MarkUtilityAsPaidAsync(string utilityId, string userId, string? notes, string? bankAccountId = null)
        {
            try
            {
                var utility = await _context.Utilities
                    .FirstOrDefaultAsync(u => u.Id == utilityId && u.UserId == userId && !u.IsDeleted);

                if (utility == null)
                {
                    return ApiResponse<UtilityDto>.ErrorResult("Utility not found");
                }

                utility.Status = "PAID";
                utility.PaidAt = DateTime.UtcNow;
                utility.UpdatedAt = DateTime.UtcNow;
                if (!string.IsNullOrEmpty(notes))
                {
                    utility.Notes = notes;
                }

                await _context.SaveChangesAsync();

                // Create payment accounting entry
                if (!string.IsNullOrEmpty(bankAccountId))
                {
                    // Get bank account name if bankAccountId is provided
                    string? bankAccountName = null;
                    var bankAccount = await _context.BankAccounts
                        .FirstOrDefaultAsync(b => b.Id == bankAccountId && b.UserId == userId);
                    if (bankAccount != null)
                    {
                        bankAccountName = bankAccount.AccountName;
                    }

                    await _accountingService.CreateBillPaymentEntryAsync(
                        utility.Id,
                        userId,
                        utility.Amount,
                        utility.UtilityName,
                        "UTILITY",
                        bankAccountName,
                        null,
                        $"Utility payment: {utility.UtilityName}",
                        DateTime.UtcNow
                    );
                }

                var utilityDto = MapToDto(utility);
                return ApiResponse<UtilityDto>.SuccessResult(utilityDto, "Utility marked as paid");
            }
            catch (Exception ex)
            {
                return ApiResponse<UtilityDto>.ErrorResult($"Failed to mark utility as paid: {ex.Message}");
            }
        }

        public async Task<ApiResponse<bool>> UpdateUtilityStatusAsync(string utilityId, string status, string userId)
        {
            try
            {
                var utility = await _context.Utilities
                    .FirstOrDefaultAsync(u => u.Id == utilityId && u.UserId == userId && !u.IsDeleted);

                if (utility == null)
                {
                    return ApiResponse<bool>.ErrorResult("Utility not found");
                }

                utility.Status = status.ToUpper();
                utility.UpdatedAt = DateTime.UtcNow;

                if (status.ToUpper() == "PAID" && !utility.PaidAt.HasValue)
                {
                    utility.PaidAt = DateTime.UtcNow;
                }

                await _context.SaveChangesAsync();
                return ApiResponse<bool>.SuccessResult(true, "Utility status updated");
            }
            catch (Exception ex)
            {
                return ApiResponse<bool>.ErrorResult($"Failed to update utility status: {ex.Message}");
            }
        }

        public async Task<ApiResponse<List<UtilityDto>>> GetOverdueUtilitiesAsync(string userId)
        {
            try
            {
                var now = DateTime.UtcNow;
                var utilities = await _context.Utilities
                    .Where(u => u.UserId == userId && 
                               u.Status == "PENDING" && 
                               u.DueDate < now && 
                               !u.IsDeleted)
                    .OrderBy(u => u.DueDate)
                    .ToListAsync();

                var utilityDtos = utilities.Select(MapToDto).ToList();
                return ApiResponse<List<UtilityDto>>.SuccessResult(utilityDtos);
            }
            catch (Exception ex)
            {
                return ApiResponse<List<UtilityDto>>.ErrorResult($"Failed to get overdue utilities: {ex.Message}");
            }
        }

        public async Task<ApiResponse<List<UtilityDto>>> GetUpcomingUtilitiesAsync(string userId, int days = 7)
        {
            try
            {
                var now = DateTime.UtcNow;
                var endDate = now.AddDays(days);
                var utilities = await _context.Utilities
                    .Where(u => u.UserId == userId && 
                               u.Status == "PENDING" && 
                               u.DueDate >= now && 
                               u.DueDate <= endDate && 
                               !u.IsDeleted)
                    .OrderBy(u => u.DueDate)
                    .ToListAsync();

                var utilityDtos = utilities.Select(MapToDto).ToList();
                return ApiResponse<List<UtilityDto>>.SuccessResult(utilityDtos);
            }
            catch (Exception ex)
            {
                return ApiResponse<List<UtilityDto>>.ErrorResult($"Failed to get upcoming utilities: {ex.Message}");
            }
        }

        public async Task<ApiResponse<UtilityConsumptionHistoryDto>> GetConsumptionHistoryAsync(string utilityId, string userId, int months = 12)
        {
            try
            {
                var utility = await _context.Utilities
                    .FirstOrDefaultAsync(u => u.Id == utilityId && u.UserId == userId && !u.IsDeleted);

                if (utility == null)
                {
                    return ApiResponse<UtilityConsumptionHistoryDto>.ErrorResult("Utility not found");
                }

                var cutoffDate = DateTime.UtcNow.AddMonths(-months);
                var history = await _context.Utilities
                    .Where(u => u.UserId == userId && 
                               u.UtilityType == utility.UtilityType && 
                               u.Provider == utility.Provider &&
                               u.BillingDate >= cutoffDate &&
                               !u.IsDeleted)
                    .OrderBy(u => u.BillingDate)
                    .ToListAsync();

                var dataPoints = history.Select(u => new ConsumptionDataPointDto
                {
                    BillingDate = u.BillingDate,
                    Consumption = u.Consumption,
                    Amount = u.Amount,
                    CostPerUnit = u.CostPerUnit,
                    PreviousReading = u.PreviousReading,
                    CurrentReading = u.CurrentReading,
                    Status = u.Status
                }).ToList();

                var avgConsumption = history.Where(u => u.Consumption.HasValue).Average(u => u.Consumption);
                var avgCost = history.Average(u => u.Amount);
                var avgCostPerUnit = history.Where(u => u.CostPerUnit.HasValue).Average(u => u.CostPerUnit);

                // Calculate trend (comparing first half vs second half)
                decimal? trendPercentage = null;
                if (dataPoints.Count >= 2)
                {
                    var firstHalf = dataPoints.Take(dataPoints.Count / 2).Where(d => d.Consumption.HasValue).Average(d => d.Consumption);
                    var secondHalf = dataPoints.Skip(dataPoints.Count / 2).Where(d => d.Consumption.HasValue).Average(d => d.Consumption);
                    if (firstHalf.HasValue && secondHalf.HasValue && firstHalf.Value > 0)
                    {
                        trendPercentage = ((secondHalf.Value - firstHalf.Value) / firstHalf.Value) * 100;
                    }
                }

                var historyDto = new UtilityConsumptionHistoryDto
                {
                    UtilityId = utility.Id,
                    UtilityName = utility.UtilityName,
                    UtilityType = utility.UtilityType,
                    Provider = utility.Provider,
                    History = dataPoints,
                    AverageConsumption = avgConsumption,
                    AverageCost = avgCost,
                    AverageCostPerUnit = avgCostPerUnit,
                    TrendPercentage = trendPercentage
                };

                return ApiResponse<UtilityConsumptionHistoryDto>.SuccessResult(historyDto);
            }
            catch (Exception ex)
            {
                return ApiResponse<UtilityConsumptionHistoryDto>.ErrorResult($"Failed to get consumption history: {ex.Message}");
            }
        }

        public async Task<ApiResponse<List<UtilityConsumptionHistoryDto>>> GetAllConsumptionHistoryAsync(string userId, string? utilityType = null, int months = 12)
        {
            try
            {
                var cutoffDate = DateTime.UtcNow.AddMonths(-months);
                var query = _context.Utilities
                    .Where(u => u.UserId == userId && u.BillingDate >= cutoffDate && !u.IsDeleted);

                if (!string.IsNullOrEmpty(utilityType))
                {
                    query = query.Where(u => u.UtilityType == utilityType.ToUpper());
                }

                var utilities = await query.ToListAsync();
                var grouped = utilities.GroupBy(u => new { u.UtilityType, u.Provider });

                var historyList = new List<UtilityConsumptionHistoryDto>();

                foreach (var group in grouped)
                {
                    var history = group.OrderBy(u => u.BillingDate).ToList();
                    var dataPoints = history.Select(u => new ConsumptionDataPointDto
                    {
                        BillingDate = u.BillingDate,
                        Consumption = u.Consumption,
                        Amount = u.Amount,
                        CostPerUnit = u.CostPerUnit,
                        PreviousReading = u.PreviousReading,
                        CurrentReading = u.CurrentReading,
                        Status = u.Status
                    }).ToList();

                    var avgConsumption = history.Where(u => u.Consumption.HasValue).Average(u => u.Consumption);
                    var avgCost = history.Average(u => u.Amount);
                    var avgCostPerUnit = history.Where(u => u.CostPerUnit.HasValue).Average(u => u.CostPerUnit);

                    decimal? trendPercentage = null;
                    if (dataPoints.Count >= 2)
                    {
                        var firstHalf = dataPoints.Take(dataPoints.Count / 2).Where(d => d.Consumption.HasValue).Average(d => d.Consumption);
                        var secondHalf = dataPoints.Skip(dataPoints.Count / 2).Where(d => d.Consumption.HasValue).Average(d => d.Consumption);
                        if (firstHalf.HasValue && secondHalf.HasValue && firstHalf.Value > 0)
                        {
                            trendPercentage = ((secondHalf.Value - firstHalf.Value) / firstHalf.Value) * 100;
                        }
                    }

                    historyList.Add(new UtilityConsumptionHistoryDto
                    {
                        UtilityId = history.First().Id,
                        UtilityName = $"{group.Key.UtilityType} - {group.Key.Provider}",
                        UtilityType = group.Key.UtilityType,
                        Provider = group.Key.Provider,
                        History = dataPoints,
                        AverageConsumption = avgConsumption,
                        AverageCost = avgCost,
                        AverageCostPerUnit = avgCostPerUnit,
                        TrendPercentage = trendPercentage
                    });
                }

                return ApiResponse<List<UtilityConsumptionHistoryDto>>.SuccessResult(historyList);
            }
            catch (Exception ex)
            {
                return ApiResponse<List<UtilityConsumptionHistoryDto>>.ErrorResult($"Failed to get consumption history: {ex.Message}");
            }
        }

        public async Task<ApiResponse<UtilityComparisonDto>> CompareProvidersAsync(string userId, string utilityType)
        {
            try
            {
                var utilities = await _context.Utilities
                    .Where(u => u.UserId == userId && 
                               u.UtilityType == utilityType.ToUpper() && 
                               !u.IsDeleted)
                    .ToListAsync();

                if (!utilities.Any())
                {
                    return ApiResponse<UtilityComparisonDto>.ErrorResult("No utilities found for comparison");
                }

                var providers = utilities
                    .GroupBy(u => u.Provider)
                    .Select(g => new ProviderComparisonDto
                    {
                        Provider = g.Key,
                        AverageAmount = g.Average(u => u.Amount),
                        AverageConsumption = g.Where(u => u.Consumption.HasValue).Average(u => u.Consumption),
                        AverageCostPerUnit = g.Where(u => u.CostPerUnit.HasValue).Average(u => u.CostPerUnit),
                        BillCount = g.Count(),
                        LastBillDate = g.Max(u => u.BillingDate),
                        TotalSpent = g.Sum(u => u.Amount)
                    })
                    .OrderBy(p => p.AverageAmount)
                    .ToList();

                var averageCost = utilities.Average(u => u.Amount);
                var averageConsumption = utilities.Where(u => u.Consumption.HasValue).Average(u => u.Consumption);
                var averageCostPerUnit = utilities.Where(u => u.CostPerUnit.HasValue).Average(u => u.CostPerUnit);

                var recommendedProvider = providers.OrderBy(p => p.AverageAmount).FirstOrDefault()?.Provider;
                var potentialSavings = recommendedProvider != null
                    ? averageCost - providers.First(p => p.Provider == recommendedProvider).AverageAmount
                    : (decimal?)null;

                var comparison = new UtilityComparisonDto
                {
                    UtilityType = utilityType.ToUpper(),
                    Providers = providers,
                    AverageCost = averageCost,
                    AverageConsumption = averageConsumption,
                    AverageCostPerUnit = averageCostPerUnit,
                    RecommendedProvider = recommendedProvider,
                    PotentialSavings = potentialSavings
                };

                return ApiResponse<UtilityComparisonDto>.SuccessResult(comparison);
            }
            catch (Exception ex)
            {
                return ApiResponse<UtilityComparisonDto>.ErrorResult($"Failed to compare providers: {ex.Message}");
            }
        }

        public async Task<ApiResponse<List<UtilityComparisonDto>>> CompareAllUtilityTypesAsync(string userId)
        {
            try
            {
                var utilities = await _context.Utilities
                    .Where(u => u.UserId == userId && !u.IsDeleted)
                    .ToListAsync();

                var comparisons = utilities
                    .GroupBy(u => u.UtilityType)
                    .Select(g =>
                    {
                        var typeUtilities = g.ToList();
                        var providers = typeUtilities
                            .GroupBy(u => u.Provider)
                            .Select(p => new ProviderComparisonDto
                            {
                                Provider = p.Key,
                                AverageAmount = p.Average(u => u.Amount),
                                AverageConsumption = p.Where(u => u.Consumption.HasValue).Average(u => u.Consumption),
                                AverageCostPerUnit = p.Where(u => u.CostPerUnit.HasValue).Average(u => u.CostPerUnit),
                                BillCount = p.Count(),
                                LastBillDate = p.Max(u => u.BillingDate),
                                TotalSpent = p.Sum(u => u.Amount)
                            })
                            .OrderBy(p => p.AverageAmount)
                            .ToList();

                        var averageCost = typeUtilities.Average(u => u.Amount);
                        var averageConsumption = typeUtilities.Where(u => u.Consumption.HasValue).Average(u => u.Consumption);
                        var averageCostPerUnit = typeUtilities.Where(u => u.CostPerUnit.HasValue).Average(u => u.CostPerUnit);

                        var recommendedProvider = providers.OrderBy(p => p.AverageAmount).FirstOrDefault()?.Provider;
                        var potentialSavings = recommendedProvider != null
                            ? averageCost - providers.First(p => p.Provider == recommendedProvider).AverageAmount
                            : (decimal?)null;

                        return new UtilityComparisonDto
                        {
                            UtilityType = g.Key,
                            Providers = providers,
                            AverageCost = averageCost,
                            AverageConsumption = averageConsumption,
                            AverageCostPerUnit = averageCostPerUnit,
                            RecommendedProvider = recommendedProvider,
                            PotentialSavings = potentialSavings
                        };
                    })
                    .ToList();

                return ApiResponse<List<UtilityComparisonDto>>.SuccessResult(comparisons);
            }
            catch (Exception ex)
            {
                return ApiResponse<List<UtilityComparisonDto>>.ErrorResult($"Failed to compare utility types: {ex.Message}");
            }
        }

        public async Task<ApiResponse<List<ProviderComparisonDto>>> GetProviderComparisonAsync(string userId, string utilityType)
        {
            try
            {
                var utilities = await _context.Utilities
                    .Where(u => u.UserId == userId && 
                               u.UtilityType == utilityType.ToUpper() && 
                               !u.IsDeleted)
                    .ToListAsync();

                var providers = utilities
                    .GroupBy(u => u.Provider)
                    .Select(g => new ProviderComparisonDto
                    {
                        Provider = g.Key,
                        AverageAmount = g.Average(u => u.Amount),
                        AverageConsumption = g.Where(u => u.Consumption.HasValue).Average(u => u.Consumption),
                        AverageCostPerUnit = g.Where(u => u.CostPerUnit.HasValue).Average(u => u.CostPerUnit),
                        BillCount = g.Count(),
                        LastBillDate = g.Max(u => u.BillingDate),
                        TotalSpent = g.Sum(u => u.Amount)
                    })
                    .OrderBy(p => p.AverageAmount)
                    .ToList();

                return ApiResponse<List<ProviderComparisonDto>>.SuccessResult(providers);
            }
            catch (Exception ex)
            {
                return ApiResponse<List<ProviderComparisonDto>>.ErrorResult($"Failed to get provider comparison: {ex.Message}");
            }
        }

        private UtilityDto MapToDto(Utility utility)
        {
            return new UtilityDto
            {
                Id = utility.Id,
                UserId = utility.UserId,
                UtilityName = utility.UtilityName,
                UtilityType = utility.UtilityType,
                Provider = utility.Provider,
                AccountNumber = utility.AccountNumber,
                Unit = utility.Unit,
                Consumption = utility.Consumption,
                CostPerUnit = utility.CostPerUnit,
                Amount = utility.Amount,
                BillingDate = utility.BillingDate,
                DueDate = utility.DueDate,
                Status = utility.Status,
                Notes = utility.Notes,
                ReferenceNumber = utility.ReferenceNumber,
                PreviousReading = utility.PreviousReading,
                CurrentReading = utility.CurrentReading,
                ReadingDate = utility.ReadingDate,
                PropertyAddress = utility.PropertyAddress,
                MeterNumber = utility.MeterNumber,
                AutoGenerateNext = utility.AutoGenerateNext,
                IsAutoGenerated = utility.IsAutoGenerated,
                ConfirmedAt = utility.ConfirmedAt,
                ParentUtilityId = utility.ParentUtilityId,
                CreatedAt = utility.CreatedAt,
                UpdatedAt = utility.UpdatedAt,
                PaidAt = utility.PaidAt
            };
        }
    }
}

