using System.ComponentModel.DataAnnotations;

namespace UtilityHub360.DTOs
{
    /// <summary>
    /// Custom validation attribute to ensure dates are within the current year only
    /// </summary>
    public class CurrentYearOnlyAttribute : ValidationAttribute
    {
        public override bool IsValid(object? value)
        {
            if (value is DateTime date)
            {
                var currentYear = DateTime.UtcNow.Year;
                return date.Year == currentYear;
            }
            return true; // Allow null values to be handled by Required attribute
        }

        public override string FormatErrorMessage(string name)
        {
            var currentYear = DateTime.UtcNow.Year;
            return $"The {name} must be within the current year ({currentYear}). Please select a date in {currentYear}.";
        }
    }
}

namespace UtilityHub360.DTOs
{
    public class BillDto
    {
        public string Id { get; set; } = string.Empty;
        public string UserId { get; set; } = string.Empty;
        public string BillName { get; set; } = string.Empty;
        public string BillType { get; set; } = string.Empty;
        public decimal Amount { get; set; }
        public DateTime DueDate { get; set; }
        public string Frequency { get; set; } = string.Empty;
        public string Status { get; set; } = string.Empty;
        public DateTime CreatedAt { get; set; }
        public DateTime UpdatedAt { get; set; }
        public DateTime? PaidAt { get; set; }
        public string? Notes { get; set; }
        public string? Provider { get; set; }
        public string? ReferenceNumber { get; set; }
        public bool AutoGenerateNext { get; set; }
        public bool IsAutoGenerated { get; set; }
        public DateTime? ConfirmedAt { get; set; }
        public string? ParentBillId { get; set; }
        
        // Scheduled Payment
        public bool IsScheduledPayment { get; set; }
        public string? ScheduledPaymentBankAccountId { get; set; }
        public int? ScheduledPaymentDaysBeforeDue { get; set; }
        public DateTime? LastScheduledPaymentAttempt { get; set; }
        public string? ScheduledPaymentFailureReason { get; set; }
        
        // Approval Workflow
        public string ApprovalStatus { get; set; } = "APPROVED";
        public string? ApprovedBy { get; set; }
        public DateTime? ApprovedAt { get; set; }
        public string? ApprovalNotes { get; set; }
    }

    public class CreateBillDto
    {
        [Required]
        [StringLength(255)]
        public string BillName { get; set; } = string.Empty;

        [Required]
        [StringLength(50)]
        public string BillType { get; set; } = string.Empty;

        [Required]
        [Range(0.01, double.MaxValue, ErrorMessage = "Amount must be greater than 0")]
        public decimal Amount { get; set; }

        [Required]
        [CurrentYearOnly]
        public DateTime DueDate { get; set; }

        [Required]
        [StringLength(20)]
        public string Frequency { get; set; } = string.Empty;

        [StringLength(500)]
        public string? Notes { get; set; }

        [StringLength(100)]
        public string? Provider { get; set; }

        [StringLength(100)]
        public string? ReferenceNumber { get; set; }

        // Auto-generation option
        public bool AutoGenerateNext { get; set; } = false;
        
        // Scheduled Payment Configuration
        public bool IsScheduledPayment { get; set; } = false;
        public string? ScheduledPaymentBankAccountId { get; set; }
        public int? ScheduledPaymentDaysBeforeDue { get; set; } // Pay X days before due date (null = on due date)
    }

    public class MarkBillPaidDto
    {
        [StringLength(500)]
        public string? Notes { get; set; }

        [StringLength(450)]
        public string? BankAccountId { get; set; }
    }

    public class UpdateBillDto
    {
        [StringLength(255)]
        public string? BillName { get; set; }

        [StringLength(50)]
        public string? BillType { get; set; }

        [Range(0.01, double.MaxValue, ErrorMessage = "Amount must be greater than 0")]
        public decimal? Amount { get; set; }

        [CurrentYearOnly]
        public DateTime? DueDate { get; set; }

        [StringLength(20)]
        public string? Frequency { get; set; }

        [StringLength(20)]
        public string? Status { get; set; }

        [StringLength(500)]
        public string? Notes { get; set; }

        [StringLength(100)]
        public string? Provider { get; set; }

        [StringLength(100)]
        public string? ReferenceNumber { get; set; }

        public bool? AutoGenerateNext { get; set; }
    }

    /// <summary>
    /// DTO for updating a specific month's bill amount
    /// Used for variable monthly billing
    /// </summary>
    public class UpdateMonthlyBillDto
    {
        [Required]
        [Range(0.01, double.MaxValue, ErrorMessage = "Amount must be greater than 0")]
        public decimal Amount { get; set; }

        [StringLength(500)]
        public string? Notes { get; set; }

        [StringLength(20)]
        public string? Status { get; set; }
    }

    /// <summary>
    /// DTO for quickly updating auto-generated bill amount
    /// </summary>
    public class ConfirmBillAmountDto
    {
        [Required]
        [Range(0.01, double.MaxValue, ErrorMessage = "Amount must be greater than 0")]
        public decimal Amount { get; set; }

        [StringLength(500)]
        public string? Notes { get; set; }
    }

    public class BillAnalyticsDto
    {
        public decimal TotalPendingAmount { get; set; }
        public decimal TotalPaidAmount { get; set; }
        public decimal TotalOverdueAmount { get; set; }
        public int TotalPendingBills { get; set; }
        public int TotalPaidBills { get; set; }
        public int TotalOverdueBills { get; set; }
        public DateTime GeneratedAt { get; set; } = DateTime.UtcNow;
    }

    public class BillSummaryDto
    {
        public decimal Amount { get; set; }
        public int Count { get; set; }
        public string Period { get; set; } = string.Empty;
        public DateTime StartDate { get; set; }
        public DateTime EndDate { get; set; }
    }

    // Bill Payment DTOs
    public class CreateBillPaymentDto
    {
        [Required]
        public string BillId { get; set; } = string.Empty;

        [Required]
        [Range(0.01, double.MaxValue, ErrorMessage = "Amount must be greater than 0")]
        public decimal Amount { get; set; }

        [Required]
        [StringLength(50)]
        public string Method { get; set; } = string.Empty; // BANK_TRANSFER, CARD, WALLET, CASH

        [Required]
        [StringLength(50)]
        public string Reference { get; set; } = string.Empty;

        [StringLength(450)]
        public string? BankAccountId { get; set; } // Required for bank transfers

        [StringLength(500)]
        public string? Notes { get; set; }
    }

    public class BillPaymentDto
    {
        public string Id { get; set; } = string.Empty;
        public string BillId { get; set; } = string.Empty;
        public string? BankAccountId { get; set; }
        public string UserId { get; set; } = string.Empty;
        public decimal Amount { get; set; }
        public string Method { get; set; } = string.Empty;
        public string Reference { get; set; } = string.Empty;
        public string Status { get; set; } = string.Empty;
        public bool IsBankTransaction { get; set; }
        public string? TransactionType { get; set; }
        public string? Description { get; set; }
        public string? Category { get; set; }
        public string? ExternalTransactionId { get; set; }
        public string? Notes { get; set; }
        public string? Merchant { get; set; }
        public string? Location { get; set; }
        public bool IsRecurring { get; set; }
        public string? RecurringFrequency { get; set; }
        public string Currency { get; set; } = string.Empty;
        public decimal? BalanceAfterTransaction { get; set; }
        public DateTime ProcessedAt { get; set; }
        public DateTime? TransactionDate { get; set; }
        public DateTime CreatedAt { get; set; }
        public DateTime UpdatedAt { get; set; }
    }

    // Cleanup DTOs
    public class CleanupResultDto
    {
        public int DeletedBillsCount { get; set; }
        public int DeletedPaymentsCount { get; set; }
        public int DeletedAlertsCount { get; set; }
        public string Message { get; set; } = string.Empty;
    }

    public class OutOfYearBillsCountDto
    {
        public int Count { get; set; }
        public int CurrentYear { get; set; }
        public string Message { get; set; } = string.Empty;
    }

    public class DateRangeBillsCountDto
    {
        public int Count { get; set; }
        public DateTime StartDate { get; set; }
        public DateTime EndDate { get; set; }
        public string Message { get; set; } = string.Empty;
    }
}
