namespace UtilityHub360.DTOs
{
    public class UtilityDto
    {
        public string Id { get; set; } = string.Empty;
        public string UserId { get; set; } = string.Empty;
        public string UtilityName { get; set; } = string.Empty;
        public string UtilityType { get; set; } = string.Empty;
        public string Provider { get; set; } = string.Empty;
        public string? AccountNumber { get; set; }
        public string? Unit { get; set; }
        public decimal? Consumption { get; set; }
        public decimal? CostPerUnit { get; set; }
        public decimal Amount { get; set; }
        public DateTime BillingDate { get; set; }
        public DateTime DueDate { get; set; }
        public string Status { get; set; } = string.Empty;
        public string? Notes { get; set; }
        public string? ReferenceNumber { get; set; }
        public decimal? PreviousReading { get; set; }
        public decimal? CurrentReading { get; set; }
        public DateTime? ReadingDate { get; set; }
        public string? PropertyAddress { get; set; }
        public string? MeterNumber { get; set; }
        public bool AutoGenerateNext { get; set; }
        public bool IsAutoGenerated { get; set; }
        public DateTime? ConfirmedAt { get; set; }
        public string? ParentUtilityId { get; set; }
        public DateTime CreatedAt { get; set; }
        public DateTime UpdatedAt { get; set; }
        public DateTime? PaidAt { get; set; }
    }

    public class CreateUtilityDto
    {
        public string UtilityName { get; set; } = string.Empty;
        public string UtilityType { get; set; } = string.Empty;
        public string Provider { get; set; } = string.Empty;
        public string? AccountNumber { get; set; }
        public string? Unit { get; set; }
        public decimal? Consumption { get; set; }
        public decimal? CostPerUnit { get; set; }
        public decimal Amount { get; set; }
        public DateTime BillingDate { get; set; }
        public DateTime DueDate { get; set; }
        public string? Notes { get; set; }
        public string? ReferenceNumber { get; set; }
        public decimal? PreviousReading { get; set; }
        public decimal? CurrentReading { get; set; }
        public DateTime? ReadingDate { get; set; }
        public string? PropertyAddress { get; set; }
        public string? MeterNumber { get; set; }
        public bool AutoGenerateNext { get; set; } = false;
    }

    public class UpdateUtilityDto
    {
        public string? UtilityName { get; set; }
        public string? UtilityType { get; set; }
        public string? Provider { get; set; }
        public string? AccountNumber { get; set; }
        public string? Unit { get; set; }
        public decimal? Consumption { get; set; }
        public decimal? CostPerUnit { get; set; }
        public decimal? Amount { get; set; }
        public DateTime? BillingDate { get; set; }
        public DateTime? DueDate { get; set; }
        public string? Notes { get; set; }
        public string? ReferenceNumber { get; set; }
        public decimal? PreviousReading { get; set; }
        public decimal? CurrentReading { get; set; }
        public DateTime? ReadingDate { get; set; }
        public string? PropertyAddress { get; set; }
        public string? MeterNumber { get; set; }
        public bool? AutoGenerateNext { get; set; }
    }

    public class UtilityComparisonDto
    {
        public string UtilityType { get; set; } = string.Empty;
        public List<ProviderComparisonDto> Providers { get; set; } = new();
        public decimal AverageCost { get; set; }
        public decimal? AverageConsumption { get; set; }
        public decimal? AverageCostPerUnit { get; set; }
        public string? RecommendedProvider { get; set; }
        public decimal? PotentialSavings { get; set; }
    }

    public class ProviderComparisonDto
    {
        public string Provider { get; set; } = string.Empty;
        public decimal AverageAmount { get; set; }
        public decimal? AverageConsumption { get; set; }
        public decimal? AverageCostPerUnit { get; set; }
        public int BillCount { get; set; }
        public DateTime? LastBillDate { get; set; }
        public decimal? TotalSpent { get; set; }
    }

    public class UtilityConsumptionHistoryDto
    {
        public string UtilityId { get; set; } = string.Empty;
        public string UtilityName { get; set; } = string.Empty;
        public string UtilityType { get; set; } = string.Empty;
        public string Provider { get; set; } = string.Empty;
        public List<ConsumptionDataPointDto> History { get; set; } = new();
        public decimal? AverageConsumption { get; set; }
        public decimal? AverageCost { get; set; }
        public decimal? AverageCostPerUnit { get; set; }
        public decimal? TrendPercentage { get; set; } // Positive = increasing, Negative = decreasing
    }

    public class ConsumptionDataPointDto
    {
        public DateTime BillingDate { get; set; }
        public decimal? Consumption { get; set; }
        public decimal Amount { get; set; }
        public decimal? CostPerUnit { get; set; }
        public decimal? PreviousReading { get; set; }
        public decimal? CurrentReading { get; set; }
        public string Status { get; set; } = string.Empty;
    }

    public class UtilityAnalyticsDto
    {
        public decimal TotalPendingAmount { get; set; }
        public decimal TotalPaidAmount { get; set; }
        public decimal TotalOverdueAmount { get; set; }
        public int TotalUtilities { get; set; }
        public int PendingCount { get; set; }
        public int PaidCount { get; set; }
        public int OverdueCount { get; set; }
        public List<UtilityTypeSummaryDto> ByType { get; set; } = new();
        public List<ProviderSummaryDto> ByProvider { get; set; } = new();
    }

    public class UtilityTypeSummaryDto
    {
        public string UtilityType { get; set; } = string.Empty;
        public decimal TotalAmount { get; set; }
        public decimal? TotalConsumption { get; set; }
        public decimal? AverageCostPerUnit { get; set; }
        public int Count { get; set; }
    }

    public class ProviderSummaryDto
    {
        public string Provider { get; set; } = string.Empty;
        public string UtilityType { get; set; } = string.Empty;
        public decimal TotalAmount { get; set; }
        public decimal? TotalConsumption { get; set; }
        public decimal? AverageCostPerUnit { get; set; }
        public int Count { get; set; }
    }

    public class MarkUtilityPaidDto
    {
        public string? Notes { get; set; }
        public string? BankAccountId { get; set; }
    }
}

