

using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace UtilityHub360.Entities
{
    public class Bill
    {
        [Key]
        public string Id { get; set; } = Guid.NewGuid().ToString();

        [Required]
        [StringLength(450)]
        public string UserId { get; set; } = string.Empty;

        [Required]
        [StringLength(255)]
        public string BillName { get; set; } = string.Empty;

        [Required]
        [StringLength(50)]
        public string BillType { get; set; } = string.Empty; // utility, subscription, loan, others

        [Required]
        [Column(TypeName = "decimal(18,2)")]
        public decimal Amount { get; set; }

        [Required]
        public DateTime DueDate { get; set; }

        [Required]
        [StringLength(20)]
        public string Frequency { get; set; } = string.Empty; // monthly, quarterly, yearly

        [Required]
        [StringLength(20)]
        public string Status { get; set; } = "PENDING"; // pending, paid, overdue

        public DateTime CreatedAt { get; set; } = DateTime.UtcNow;

        public DateTime UpdatedAt { get; set; } = DateTime.UtcNow;

        public DateTime? PaidAt { get; set; }

        [StringLength(500)]
        public string? Notes { get; set; }

        [StringLength(100)]
        public string? Provider { get; set; } // Company/Service provider name

        [StringLength(100)]
        public string? ReferenceNumber { get; set; } // Account number, subscription ID, etc.

        // Auto-generation for recurring bills
        public bool AutoGenerateNext { get; set; } = false; // Enable auto-generation of next month's bill

        public bool IsAutoGenerated { get; set; } = false; // Flag to indicate if this bill was auto-generated

        public DateTime? ConfirmedAt { get; set; } // When user confirmed auto-generated bill

        // Parent-Child relationship for auto-generated bills
        [StringLength(450)]
        public string? ParentBillId { get; set; } // Links auto-generated bills to their parent

        // Scheduled Payment Configuration
        public bool IsScheduledPayment { get; set; } = false; // Enable automatic payment
        [StringLength(450)]
        public string? ScheduledPaymentBankAccountId { get; set; } // Bank account to use for automatic payment
        public int? ScheduledPaymentDaysBeforeDue { get; set; } // Pay X days before due date (null = on due date)
        public DateTime? LastScheduledPaymentAttempt { get; set; } // Last time system tried to pay
        [StringLength(500)]
        public string? ScheduledPaymentFailureReason { get; set; } // Reason if scheduled payment failed

        // Bill Approval Workflow
        [StringLength(20)]
        public string ApprovalStatus { get; set; } = "APPROVED"; // APPROVED, PENDING_APPROVAL, REJECTED
        [StringLength(450)]
        public string? ApprovedBy { get; set; } // User who approved
        public DateTime? ApprovedAt { get; set; } // When approved
        [StringLength(500)]
        public string? ApprovalNotes { get; set; } // Approval/rejection notes

        // Soft Delete Properties
        public bool IsDeleted { get; set; } = false;
        public DateTime? DeletedAt { get; set; }
        
        [StringLength(450)]
        public string? DeletedBy { get; set; } // User who deleted it
        
        [StringLength(500)]
        public string? DeleteReason { get; set; } // Why it was deleted/voided

        // Navigation property
        [ForeignKey("UserId")]
        public virtual User User { get; set; } = null!;
    }
}
