using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace UtilityHub360.Entities
{
    public class Utility
    {
        [Key]
        public string Id { get; set; } = Guid.NewGuid().ToString();

        [Required]
        [StringLength(450)]
        public string UserId { get; set; } = string.Empty;

        [Required]
        [StringLength(100)]
        public string UtilityName { get; set; } = string.Empty; // e.g., "Electricity", "Water", "Gas"

        [Required]
        [StringLength(50)]
        public string UtilityType { get; set; } = string.Empty; // ELECTRICITY, WATER, GAS, INTERNET, PHONE, SEWER, TRASH

        [Required]
        [StringLength(100)]
        public string Provider { get; set; } = string.Empty; // Provider company name

        [StringLength(100)]
        public string? AccountNumber { get; set; } // Account number with provider

        [StringLength(50)]
        public string? Unit { get; set; } // kWh, gallons, therms, MB, etc.

        [Column(TypeName = "decimal(18,4)")]
        public decimal? Consumption { get; set; } // Units consumed (kWh, gallons, etc.)

        [Column(TypeName = "decimal(18,4)")]
        public decimal? CostPerUnit { get; set; } // Cost per unit (e.g., $0.12 per kWh)

        [Required]
        [Column(TypeName = "decimal(18,2)")]
        public decimal Amount { get; set; } // Total bill amount

        [Required]
        public DateTime BillingDate { get; set; } // Date of the bill

        [Required]
        public DateTime DueDate { get; set; }

        [Required]
        [StringLength(20)]
        public string Status { get; set; } = "PENDING"; // PENDING, PAID, OVERDUE

        [StringLength(500)]
        public string? Notes { get; set; }

        [StringLength(100)]
        public string? ReferenceNumber { get; set; } // Bill reference number

        // Consumption tracking
        [Column(TypeName = "decimal(18,4)")]
        public decimal? PreviousReading { get; set; } // Previous meter reading

        [Column(TypeName = "decimal(18,4)")]
        public decimal? CurrentReading { get; set; } // Current meter reading

        public DateTime? ReadingDate { get; set; } // Date of meter reading

        // Location/Property information
        [StringLength(255)]
        public string? PropertyAddress { get; set; }

        [StringLength(50)]
        public string? MeterNumber { get; set; }

        // Auto-generation for recurring utilities
        public bool AutoGenerateNext { get; set; } = false;

        public bool IsAutoGenerated { get; set; } = false;

        public DateTime? ConfirmedAt { get; set; }

        [StringLength(450)]
        public string? ParentUtilityId { get; set; } // Links auto-generated utilities to their parent

        // Timestamps
        public DateTime CreatedAt { get; set; } = DateTime.UtcNow;

        public DateTime UpdatedAt { get; set; } = DateTime.UtcNow;

        public DateTime? PaidAt { get; set; }

        // Soft Delete
        public bool IsDeleted { get; set; } = false;

        public DateTime? DeletedAt { get; set; }

        [StringLength(450)]
        public string? DeletedBy { get; set; }

        [StringLength(500)]
        public string? DeleteReason { get; set; }

        // Navigation property
        [ForeignKey("UserId")]
        public virtual User User { get; set; } = null!;
    }
}

