-- Create Utilities Table
-- This migration creates a separate Utilities table for tracking utility bills with consumption data

IF NOT EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[Utilities]') AND type in (N'U'))
BEGIN
    CREATE TABLE [dbo].[Utilities] (
        [Id] NVARCHAR(450) NOT NULL,
        [UserId] NVARCHAR(450) NOT NULL,
        [UtilityName] NVARCHAR(100) NOT NULL,
        [UtilityType] NVARCHAR(50) NOT NULL,
        [Provider] NVARCHAR(100) NOT NULL,
        [AccountNumber] NVARCHAR(100) NULL,
        [Unit] NVARCHAR(50) NULL,
        [Consumption] DECIMAL(18,4) NULL,
        [CostPerUnit] DECIMAL(18,4) NULL,
        [Amount] DECIMAL(18,2) NOT NULL,
        [BillingDate] DATETIME2 NOT NULL,
        [DueDate] DATETIME2 NOT NULL,
        [Status] NVARCHAR(20) NOT NULL DEFAULT 'PENDING',
        [Notes] NVARCHAR(500) NULL,
        [ReferenceNumber] NVARCHAR(100) NULL,
        [PreviousReading] DECIMAL(18,4) NULL,
        [CurrentReading] DECIMAL(18,4) NULL,
        [ReadingDate] DATETIME2 NULL,
        [PropertyAddress] NVARCHAR(255) NULL,
        [MeterNumber] NVARCHAR(50) NULL,
        [AutoGenerateNext] BIT NOT NULL DEFAULT 0,
        [IsAutoGenerated] BIT NOT NULL DEFAULT 0,
        [ConfirmedAt] DATETIME2 NULL,
        [ParentUtilityId] NVARCHAR(450) NULL,
        [CreatedAt] DATETIME2 NOT NULL,
        [UpdatedAt] DATETIME2 NOT NULL,
        [PaidAt] DATETIME2 NULL,
        [IsDeleted] BIT NOT NULL DEFAULT 0,
        [DeletedAt] DATETIME2 NULL,
        [DeletedBy] NVARCHAR(450) NULL,
        [DeleteReason] NVARCHAR(500) NULL,
        CONSTRAINT [PK_Utilities] PRIMARY KEY CLUSTERED ([Id] ASC)
    );

    -- Create indexes for better query performance
    CREATE INDEX [IX_Utilities_UserId] ON [dbo].[Utilities] ([UserId]);
    CREATE INDEX [IX_Utilities_UtilityType] ON [dbo].[Utilities] ([UtilityType]);
    CREATE INDEX [IX_Utilities_Provider] ON [dbo].[Utilities] ([Provider]);
    CREATE INDEX [IX_Utilities_Status] ON [dbo].[Utilities] ([Status]);
    CREATE INDEX [IX_Utilities_BillingDate] ON [dbo].[Utilities] ([BillingDate]);
    CREATE INDEX [IX_Utilities_DueDate] ON [dbo].[Utilities] ([DueDate]);
    CREATE INDEX [IX_Utilities_UserId_UtilityType_Provider] ON [dbo].[Utilities] ([UserId], [UtilityType], [Provider]);

    -- Add foreign key constraint
    ALTER TABLE [dbo].[Utilities]
    ADD CONSTRAINT [FK_Utilities_Users_UserId] 
    FOREIGN KEY ([UserId]) REFERENCES [dbo].[Users] ([Id]) ON DELETE CASCADE;

    PRINT 'Utilities table created successfully';
END
ELSE
BEGIN
    PRINT 'Utilities table already exists';
END
GO

