-- ====================================================================
-- DELETE AUTO-GENERATED BILLS FROM JANUARY 2026 TO DECEMBER 2031
-- ====================================================================
-- ⚠️ WARNING: This will permanently delete auto-generated bills and related data
-- Make sure to backup your database before running this script!

USE UtilityHub360; -- Replace with your actual database name

BEGIN TRANSACTION;

PRINT 'Starting deletion of auto-generated bills from January 2026 to December 2031...';

-- Step 1: Get count of bills to be deleted (for reporting)
DECLARE @BillCount INT;
SELECT @BillCount = COUNT(*)
FROM Bills 
WHERE IsAutoGenerated = 1 
  AND DueDate >= '2026-01-01' 
  AND DueDate <= '2031-12-31';

PRINT 'Found ' + CAST(@BillCount AS VARCHAR(10)) + ' auto-generated bills to delete';

-- Step 2: Delete related BankTransactions first (to maintain referential integrity)
DELETE bt FROM BankTransactions bt
INNER JOIN Payments p ON bt.ReferenceNumber = p.Reference
INNER JOIN Bills b ON p.BillId = b.Id
WHERE b.IsAutoGenerated = 1 
  AND b.DueDate >= '2026-01-01' 
  AND b.DueDate <= '2031-12-31';

PRINT 'Deleted related bank transactions';

-- Step 3: Reverse bank account balances for deleted payments
UPDATE ba SET 
  CurrentBalance = CurrentBalance + p.Amount,
  UpdatedAt = GETUTCDATE()
FROM BankAccounts ba
INNER JOIN Payments p ON ba.Id = p.BankAccountId
INNER JOIN Bills b ON p.BillId = b.Id
WHERE b.IsAutoGenerated = 1 
  AND b.DueDate >= '2026-01-01' 
  AND b.DueDate <= '2031-12-31'
  AND p.IsBankTransaction = 1;

PRINT 'Reversed bank account balances';

-- Step 4: Delete related Payments
DELETE p FROM Payments p
INNER JOIN Bills b ON p.BillId = b.Id
WHERE b.IsAutoGenerated = 1 
  AND b.DueDate >= '2026-01-01' 
  AND b.DueDate <= '2031-12-31';

PRINT 'Deleted related payments';

-- Step 5: Delete related BillAlerts
DELETE ba FROM BillAlerts ba
INNER JOIN Bills b ON ba.BillId = b.Id
WHERE b.IsAutoGenerated = 1 
  AND b.DueDate >= '2026-01-01' 
  AND b.DueDate <= '2031-12-31';

PRINT 'Deleted related bill alerts';

-- Step 6: Finally, delete the Bills themselves
DELETE FROM Bills 
WHERE IsAutoGenerated = 1 
  AND DueDate >= '2026-01-01' 
  AND DueDate <= '2031-12-31';

PRINT 'Deleted ' + CAST(@BillCount AS VARCHAR(10)) + ' auto-generated bills';

-- Step 7: Verify deletion
DECLARE @RemainingCount INT;
SELECT @RemainingCount = COUNT(*)
FROM Bills 
WHERE IsAutoGenerated = 1 
  AND DueDate >= '2026-01-01' 
  AND DueDate <= '2031-12-31';

IF @RemainingCount = 0
BEGIN
    PRINT 'SUCCESS: All auto-generated bills from 2026-2031 have been deleted';
    COMMIT TRANSACTION;
END
ELSE
BEGIN
    PRINT 'WARNING: ' + CAST(@RemainingCount AS VARCHAR(10)) + ' bills still remain. Rolling back...';
    ROLLBACK TRANSACTION;
END

PRINT 'Deletion process completed.';

-- Optional: Check what bills remain in reasonable date ranges
SELECT 
    YEAR(DueDate) as Year,
    COUNT(*) as BillCount,
    COUNT(CASE WHEN IsAutoGenerated = 1 THEN 1 END) as AutoGeneratedCount
FROM Bills 
WHERE DueDate >= '2024-01-01' AND DueDate <= '2025-12-31'
GROUP BY YEAR(DueDate)
ORDER BY Year;

PRINT 'Summary of remaining bills in 2024-2025 (reasonable range)';
