using System;
using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace UtilityHub360.Migrations
{
    /// <inheritdoc />
    public partial class AddAutoGenerationFieldsToBills : Migration
    {
        /// <inheritdoc />
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.AddColumn<bool>(
                name: "AutoGenerateNext",
                table: "Bills",
                type: "bit",
                nullable: false,
                defaultValue: false);

            migrationBuilder.AddColumn<DateTime>(
                name: "ConfirmedAt",
                table: "Bills",
                type: "datetime2",
                nullable: true);

            migrationBuilder.AddColumn<bool>(
                name: "IsAutoGenerated",
                table: "Bills",
                type: "bit",
                nullable: false,
                defaultValue: false);

            migrationBuilder.CreateTable(
                name: "BillAlerts",
                columns: table => new
                {
                    Id = table.Column<string>(type: "nvarchar(450)", nullable: false),
                    UserId = table.Column<string>(type: "nvarchar(450)", maxLength: 450, nullable: false),
                    AlertType = table.Column<string>(type: "nvarchar(50)", maxLength: 50, nullable: false),
                    Severity = table.Column<string>(type: "nvarchar(20)", maxLength: 20, nullable: false),
                    Title = table.Column<string>(type: "nvarchar(200)", maxLength: 200, nullable: false),
                    Message = table.Column<string>(type: "nvarchar(1000)", maxLength: 1000, nullable: false),
                    BillId = table.Column<string>(type: "nvarchar(450)", maxLength: 450, nullable: true),
                    Provider = table.Column<string>(type: "nvarchar(100)", maxLength: 100, nullable: true),
                    Amount = table.Column<decimal>(type: "decimal(18,2)", nullable: true),
                    CreatedAt = table.Column<DateTime>(type: "datetime2", nullable: false),
                    IsRead = table.Column<bool>(type: "bit", nullable: false),
                    ActionLink = table.Column<string>(type: "nvarchar(500)", maxLength: 500, nullable: true)
                },
                constraints: table =>
                {
                    table.PrimaryKey("PK_BillAlerts", x => x.Id);
                    table.ForeignKey(
                        name: "FK_BillAlerts_Bills_BillId",
                        column: x => x.BillId,
                        principalTable: "Bills",
                        principalColumn: "Id");
                    table.ForeignKey(
                        name: "FK_BillAlerts_Users_UserId",
                        column: x => x.UserId,
                        principalTable: "Users",
                        principalColumn: "Id",
                        onDelete: ReferentialAction.Cascade);
                });

            migrationBuilder.CreateTable(
                name: "BillAnalyticsCaches",
                columns: table => new
                {
                    Id = table.Column<string>(type: "nvarchar(450)", nullable: false),
                    UserId = table.Column<string>(type: "nvarchar(450)", maxLength: 450, nullable: false),
                    Provider = table.Column<string>(type: "nvarchar(100)", maxLength: 100, nullable: false),
                    BillType = table.Column<string>(type: "nvarchar(50)", maxLength: 50, nullable: false),
                    CalculationMonth = table.Column<DateTime>(type: "datetime2", nullable: false),
                    SimpleAverage = table.Column<decimal>(type: "decimal(18,2)", nullable: false),
                    WeightedAverage = table.Column<decimal>(type: "decimal(18,2)", nullable: false),
                    SeasonalAverage = table.Column<decimal>(type: "decimal(18,2)", nullable: false),
                    ForecastAmount = table.Column<decimal>(type: "decimal(18,2)", nullable: false),
                    TotalSpent = table.Column<decimal>(type: "decimal(18,2)", nullable: false),
                    HighestBill = table.Column<decimal>(type: "decimal(18,2)", nullable: false),
                    LowestBill = table.Column<decimal>(type: "decimal(18,2)", nullable: false),
                    Trend = table.Column<string>(type: "nvarchar(20)", maxLength: 20, nullable: false),
                    BillCount = table.Column<int>(type: "int", nullable: false),
                    CalculatedAt = table.Column<DateTime>(type: "datetime2", nullable: false)
                },
                constraints: table =>
                {
                    table.PrimaryKey("PK_BillAnalyticsCaches", x => x.Id);
                    table.ForeignKey(
                        name: "FK_BillAnalyticsCaches_Users_UserId",
                        column: x => x.UserId,
                        principalTable: "Users",
                        principalColumn: "Id",
                        onDelete: ReferentialAction.Cascade);
                });

            migrationBuilder.CreateTable(
                name: "BudgetSettings",
                columns: table => new
                {
                    Id = table.Column<string>(type: "nvarchar(450)", nullable: false),
                    UserId = table.Column<string>(type: "nvarchar(450)", maxLength: 450, nullable: false),
                    Provider = table.Column<string>(type: "nvarchar(100)", maxLength: 100, nullable: false),
                    BillType = table.Column<string>(type: "nvarchar(50)", maxLength: 50, nullable: false),
                    MonthlyBudget = table.Column<decimal>(type: "decimal(18,2)", nullable: false),
                    EnableAlerts = table.Column<bool>(type: "bit", nullable: false),
                    AlertThreshold = table.Column<int>(type: "int", nullable: false),
                    CreatedAt = table.Column<DateTime>(type: "datetime2", nullable: false),
                    UpdatedAt = table.Column<DateTime>(type: "datetime2", nullable: false)
                },
                constraints: table =>
                {
                    table.PrimaryKey("PK_BudgetSettings", x => x.Id);
                    table.ForeignKey(
                        name: "FK_BudgetSettings_Users_UserId",
                        column: x => x.UserId,
                        principalTable: "Users",
                        principalColumn: "Id",
                        onDelete: ReferentialAction.Cascade);
                });

            migrationBuilder.UpdateData(
                table: "Users",
                keyColumn: "Id",
                keyValue: "admin-001",
                columns: new[] { "CreatedAt", "UpdatedAt" },
                values: new object[] { new DateTime(2025, 10, 11, 0, 15, 55, 971, DateTimeKind.Utc).AddTicks(6829), new DateTime(2025, 10, 11, 0, 15, 55, 971, DateTimeKind.Utc).AddTicks(6829) });

            migrationBuilder.CreateIndex(
                name: "IX_BillAlerts_AlertType",
                table: "BillAlerts",
                column: "AlertType");

            migrationBuilder.CreateIndex(
                name: "IX_BillAlerts_BillId",
                table: "BillAlerts",
                column: "BillId");

            migrationBuilder.CreateIndex(
                name: "IX_BillAlerts_CreatedAt",
                table: "BillAlerts",
                column: "CreatedAt");

            migrationBuilder.CreateIndex(
                name: "IX_BillAlerts_IsRead",
                table: "BillAlerts",
                column: "IsRead");

            migrationBuilder.CreateIndex(
                name: "IX_BillAlerts_UserId",
                table: "BillAlerts",
                column: "UserId");

            migrationBuilder.CreateIndex(
                name: "IX_BillAnalyticsCaches_UserId",
                table: "BillAnalyticsCaches",
                column: "UserId");

            migrationBuilder.CreateIndex(
                name: "IX_BillAnalyticsCaches_UserId_Provider_BillType_CalculationMonth",
                table: "BillAnalyticsCaches",
                columns: new[] { "UserId", "Provider", "BillType", "CalculationMonth" },
                unique: true);

            migrationBuilder.CreateIndex(
                name: "IX_BudgetSettings_UserId",
                table: "BudgetSettings",
                column: "UserId");

            migrationBuilder.CreateIndex(
                name: "IX_BudgetSettings_UserId_Provider_BillType",
                table: "BudgetSettings",
                columns: new[] { "UserId", "Provider", "BillType" },
                unique: true);
        }

        /// <inheritdoc />
        protected override void Down(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.DropTable(
                name: "BillAlerts");

            migrationBuilder.DropTable(
                name: "BillAnalyticsCaches");

            migrationBuilder.DropTable(
                name: "BudgetSettings");

            migrationBuilder.DropColumn(
                name: "AutoGenerateNext",
                table: "Bills");

            migrationBuilder.DropColumn(
                name: "ConfirmedAt",
                table: "Bills");

            migrationBuilder.DropColumn(
                name: "IsAutoGenerated",
                table: "Bills");

            migrationBuilder.UpdateData(
                table: "Users",
                keyColumn: "Id",
                keyValue: "admin-001",
                columns: new[] { "CreatedAt", "UpdatedAt" },
                values: new object[] { new DateTime(2025, 10, 10, 22, 32, 11, 601, DateTimeKind.Utc).AddTicks(3847), new DateTime(2025, 10, 10, 22, 32, 11, 601, DateTimeKind.Utc).AddTicks(3847) });
        }
    }
}
